// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    EditorWrap: typeof import('./src/components/EditorWrap/index.vue')['default']
    FormWrap: typeof import('./src/components/FormWrap/index.vue')['default']
    MenuWrap: typeof import('./src/components/MenuWrap/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchWrap: typeof import('./src/components/SearchWrap/index.vue')['default']
    SecondWrap: typeof import('./src/components/SecondWrap/index.vue')['default']
    TButton: typeof import('tdesign-vue-next')['Button']
    TConfigProvider: typeof import('tdesign-vue-next')['ConfigProvider']
    TForm: typeof import('tdesign-vue-next')['Form']
    TFormItem: typeof import('tdesign-vue-next')['FormItem']
    THeadMenu: typeof import('tdesign-vue-next')['HeadMenu']
    TTable: typeof import('tdesign-vue-next')['Table']
    TTag: typeof import('tdesign-vue-next')['Tag']
  }
}

export {}
