/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    EditorWrap: typeof import('./src/components/EditorWrap/index.vue')['default']
    FormWrap: typeof import('./src/components/global/FormWrap/index.vue')['default']
    Hello: typeof import('./src/components/Hello.vue')['default']
    MenuWrap: typeof import('./src/components/MenuWrap/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchWrap: typeof import('./src/components/global/SearchWrap/index.vue')['default']
    SecondWrap: typeof import('./src/components/global/SecondWrap/index.vue')['default']
    TButton: typeof import('tdesign-vue-next')['Button']
    TConfigProvider: typeof import('tdesign-vue-next')['ConfigProvider']
    TForm: typeof import('tdesign-vue-next')['Form']
    TFormItem: typeof import('tdesign-vue-next')['FormItem']
    THeadMenu: typeof import('tdesign-vue-next')['HeadMenu']
    TTable: typeof import('tdesign-vue-next')['Table']
    TTag: typeof import('tdesign-vue-next')['Tag']
  }
}
